// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4692.Bastion.subsystems;

import org.usfirst.frc4692.Bastion.RobotMap;
import org.usfirst.frc4692.Bastion.commands.*;
import edu.wpi.first.wpilibj.DoubleSolenoid;

import edu.wpi.first.wpilibj.command.Subsystem;

public class Gear extends Subsystem {

    private final DoubleSolenoid slide = RobotMap.gearSlide;
    private final DoubleSolenoid spit = RobotMap.gearSpit;

    public void initDefaultCommand() {
    		
    		setDefaultCommand(new Flipdown());
    	}
    		public void Extendspit(){
    			spit.set(DoubleSolenoid.Value.kForward);
    		}
    	    public void Retractspit(){
    			spit.set(DoubleSolenoid.Value.kReverse);
    	    }
    		public void Stopspit(){
    			spit.set(DoubleSolenoid.Value.kOff);
    		}
    		public void Extendslide(){
    			slide.set(DoubleSolenoid.Value.kForward);
    		}
    	    public void Retractslide(){
    			slide.set(DoubleSolenoid.Value.kReverse);
    	    }
    		public void Stopslide(){
    			slide.set(DoubleSolenoid.Value.kOff);
    		}
    }

