// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4692.Bastion.subsystems;

import org.usfirst.frc4692.Bastion.RobotMap;
import org.usfirst.frc4692.Bastion.commands.*;
import com.ctre.CANTalon;

import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.RobotDrive;

import edu.wpi.first.wpilibj.command.Subsystem;

public class wheeldrive extends Subsystem {

    private final CANTalon leftfront = RobotMap.wheeldriveleftfront;
    private final CANTalon leftback = RobotMap.wheeldriveleftback;
    private final CANTalon rightfront = RobotMap.wheeldriverightfront;
    private final CANTalon rightback = RobotMap.wheeldriverightback;
    private final RobotDrive wheeldrive = RobotMap.wheeldrivewheeldrive;


    public void initDefaultCommand() {

        setDefaultCommand(new DriveWithJoysticks());
    }
    
    public void takeJoystickInputs(Joystick joystick1, Joystick joystick2) {
    	wheeldrive.tankDrive(joystick1, joystick2);
    }
        public void driveStraight(double d) {
        	wheeldrive.drive(3.0, 3.0);
        }
        	public void driveforward() {
        		wheeldrive.setLeftRightMotorOutputs(3.0, 3.0);
        	}
 }


