// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4692.Bastion;

import org.usfirst.frc4692.Bastion.commands.*;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.JoystickButton;



public class OI {
    
    public Joystick joystick1;
    public Joystick joystick2;
    public JoystickButton lift;
    public JoystickButton belt;
    public Joystick gamepad;
    public JoystickButton hoodflipup;
    public JoystickButton hoodflipdown;
    public JoystickButton slidein;
    public JoystickButton slideout;
    public JoystickButton gearEject;

    public OI() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS

        gamepad = new Joystick(2);
        
        slidein = new JoystickButton(gamepad, 5);
        slidein.whenPressed(new SlideRetract());
        slideout = new JoystickButton(gamepad, 7);
        slideout.whenPressed(new SlideExtend());
        gearEject = new JoystickButton(gamepad, 5);
        gearEject.whenPressed(new Spitgear());
        belt = new JoystickButton(gamepad, 1);
        belt.whenPressed(new ballbelt());
        hoodflipdown = new JoystickButton(gamepad, 2);
        hoodflipdown.whenPressed(new Flipdown());
        hoodflipup = new JoystickButton(gamepad, 3);
        hoodflipup.whenPressed(new Flipup());
        lift = new JoystickButton(gamepad, 4);
        lift.whileHeld(new Climb());
        joystick2 = new Joystick(1);
        
        joystick1 = new Joystick(0);
        


        // SmartDashboard Buttons
        SmartDashboard.putData("Autonomous", new Autonomous());
        SmartDashboard.putData("DriveWithJoysticks", new DriveWithJoysticks());
        SmartDashboard.putData("Climb", new Climb());
        SmartDashboard.putData("Flip up", new Flipup());
        SmartDashboard.putData("ballbelt", new ballbelt());
        SmartDashboard.putData("Flip down", new Flipdown());
        SmartDashboard.putData("4 wheel drive", new wheeldrive());
        SmartDashboard.putData("Spitgear", new Spitgear());
        SmartDashboard.putData("Slide Extend", new SlideExtend());
        SmartDashboard.putData("Slide Retract", new SlideRetract());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=FUNCTIONS
    public Joystick getJoystick1() {
        return joystick1;
    }

    public Joystick getJoystick2() {
        return joystick2;
    }

    public Joystick getGamepad() {
        return gamepad;
    }
}

