// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4692.Bastion;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon drivetrainleft;
    public static CANTalon drivetrainright;
    public static RobotDrive drivetrainDrive;
    public static CANTalon winchWheel;
    public static CANTalon ballstuffSpitpick;
    public static CANTalon ballstuffAgitatorright;
    public static CANTalon ballstuffAgitatorleft;
    public static DoubleSolenoid toggleHood;
    public static DoubleSolenoid gearSlide;
    public static DoubleSolenoid gearSpit;
    public static CANTalon wheeldriveleftfront;
    public static CANTalon wheeldriveleftback;
    public static CANTalon wheeldriverightfront;
    public static CANTalon wheeldriverightback;
    public static RobotDrive wheeldrivewheeldrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrainleft = new CANTalon(2);
        LiveWindow.addActuator("Drivetrain", "left", drivetrainleft);
        
        drivetrainright = new CANTalon(3);
        LiveWindow.addActuator("Drivetrain", "right", drivetrainright);
        
        drivetrainDrive = new RobotDrive(drivetrainleft, drivetrainright);
        
        drivetrainDrive.setSafetyEnabled(true);
        drivetrainDrive.setExpiration(0.1);
        drivetrainDrive.setSensitivity(0.5);
        drivetrainDrive.setMaxOutput(1.0);

        winchWheel = new CANTalon(4);
        LiveWindow.addActuator("Winch", "Wheel", winchWheel);
        
        ballstuffSpitpick = new CANTalon(5);
        LiveWindow.addActuator("Ballstuff", "Spitpick", ballstuffSpitpick);
        
        ballstuffAgitatorright = new CANTalon(6);
        LiveWindow.addActuator("Ballstuff", "Agitatorright", ballstuffAgitatorright);
        
        ballstuffAgitatorleft = new CANTalon(7);
        LiveWindow.addActuator("Ballstuff", "Agitatorleft", ballstuffAgitatorleft);
        
        toggleHood = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Toggle", "Hood", toggleHood);
        
        gearSlide = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Gear", "Slide", gearSlide);
        
        gearSpit = new DoubleSolenoid(0, 4, 5);
        LiveWindow.addActuator("Gear", "Spit", gearSpit);
        
        wheeldriveleftfront = new CANTalon(0);
        LiveWindow.addActuator("wheeldrive", "left front", wheeldriveleftfront);
        
        wheeldriveleftback = new CANTalon(1);
        LiveWindow.addActuator("wheeldrive", "left back", wheeldriveleftback);
        
        wheeldriverightfront = new CANTalon(8);
        LiveWindow.addActuator("wheeldrive", "right front", wheeldriverightfront);
        
        wheeldriverightback = new CANTalon(10);
        LiveWindow.addActuator("wheeldrive", "right back", wheeldriverightback);
        
        wheeldrivewheeldrive = new RobotDrive(wheeldriveleftfront, wheeldriveleftback,
              wheeldriverightfront, wheeldriverightback);
        
        wheeldrivewheeldrive.setSafetyEnabled(true);
        wheeldrivewheeldrive.setExpiration(0.1);
        wheeldrivewheeldrive.setSensitivity(0.5);
        wheeldrivewheeldrive.setMaxOutput(1.0);


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
