
package org.usfirst.frc4692.Bastion;

import com.ctre.CANTalon;
import edu.wpi.first.wpilibj.AnalogInput;
import edu.wpi.first.wpilibj.DoubleSolenoid;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

public class RobotMap {
    public static AnalogInput rangefinder;
    public static CANTalon drivetrainleft;
    public static CANTalon drivetrainright;
    public static RobotDrive drivetrainDrive;
    public static CANTalon winchWheel;
    public static CANTalon winchWheel1;
    public static CANTalon ballstuffSpitpick;
    public static CANTalon ballstuffAgitator;
    public static DoubleSolenoid toggleHood;
    public static DoubleSolenoid gearSlide;
    public static DoubleSolenoid gearSpit;
    public static DoubleSolenoid shiftshifter;

    public static void init() {
        rangefinder = new AnalogInput(0);
        LiveWindow.addSensor("Drivetrain", "rangefinder", rangefinder);
        drivetrainleft = new CANTalon(2);
        LiveWindow.addActuator("Drivetrain", "left", drivetrainleft);
        drivetrainright = new CANTalon(3);
        LiveWindow.addActuator("Drivetrain", "right", drivetrainright);  
        drivetrainDrive = new RobotDrive(drivetrainleft, drivetrainright);
        drivetrainDrive.setSafetyEnabled(true);
        drivetrainDrive.setExpiration(0.1);
        drivetrainDrive.setSensitivity(0.5);
        drivetrainDrive.setMaxOutput(1.0);
        winchWheel = new CANTalon(4);
        LiveWindow.addActuator("Winch", "Wheel", winchWheel);
        winchWheel1 = new CANTalon(5);
        LiveWindow.addActuator("Winch", "Wheel1", winchWheel1);
        ballstuffAgitator = new CANTalon(6);
        LiveWindow.addActuator("Ballstuff", "Spitpick", ballstuffAgitator);
        ballstuffSpitpick = new CANTalon(7);
        LiveWindow.addActuator("Ballstuff", "Agitator", ballstuffSpitpick);
        toggleHood = new DoubleSolenoid(0, 0, 1);
        LiveWindow.addActuator("Toggle", "Hood", toggleHood);
        gearSlide = new DoubleSolenoid(0, 2, 3);
        LiveWindow.addActuator("Gear", "Slide", gearSlide);  
        gearSpit = new DoubleSolenoid(0, 4, 5);
        LiveWindow.addActuator("Gear", "Spit", gearSpit);
        shiftshifter = new DoubleSolenoid(0, 6, 7);
        LiveWindow.addActuator("shift", "shifter", shiftshifter);
    }
}
